### ISSUE TITLE
After Update Get 'std::out_of_range' Error

### ISSUE THREAD

**Issue by Arlof** [zigurana/EmulationStation#10]
I previously had kids mode working great... then I upgraded the system.. and did re-compile.

Had Error On Compile:>

`
[ 74%] Building CXX object es-app/CMakeFiles/emulationstation.dir/src/FileData.cpp.o
/home/pi/RetroPie-Setup/tmp/build/emulationstation-kids/es-app/src/FileData.cpp: In member function ‘FileData* FileData::getRandom(bool, bool, bool) const’:
/home/pi/RetroPie-Setup/tmp/build/emulationstation-kids/es-app/src/FileData.cpp:190:42: warning: integer overflow in expression [-Woverflow]
  const unsigned long divisor = (RAND_MAX + 1) / n;
                                          ^
[ 75%] Building CXX object es-app/CMakeFiles/emulationstation.dir/src/FileSorts.cpp.o
`

This is the error when ES-KIDS is run... with -- debug

<
lvl3:   SystemView::populate()
lvl3:       Settings.UIMode  = Full
lvl3:       Settings.FavoritesOnly  = 1
lvl3:       filterHidden = 0
lvl3:       filterFav = 1
lvl3:       filterKid = 0
lvl3:       System = amiga
lvl3:       System = apple2
lvl3:       System = atarilynx
lvl3:       System = gamegear
lvl3:       System = macintosh
lvl3:       System = mastersystem
lvl3:       System = megadrive
lvl3:       System = nes
lvl3:       System = pc
lvl3:       System = pcengine
lvl3:       System = ports
lvl3:       System = retropie
lvl3:       System = scummvm
lvl3:       System = snes
lvl3:       System = zmachine
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)

**Comment by zigurana** [comment]
Hey, thanks for trying this out. The debug logging really helps me to pinpoint the issue as well.

The compiler warning is (kind of) harmless, I've fixed it in the latest commit anyway. The error you get is actually unrelated to it, but has more to do with a result of trying to generate a list without having anything to show.
So, based on the logging, I am guessing the bug is as follows:
You are trying to show favorites only (setting.favoritesOnly =1), but there are no favorites set (I guess).

The easy fix is to 1) change the setting for favoritesonly manually to false. 2) set at least one item to be a favorite.
I will need to make a fallback mechanism where FavoritesOnly in case of no favorites causes a nice error, or defaults to 'off' again.
It will be a couple of weeks before I am able to work on this again. But I'll see what I can do.
