### ISSUE TITLE
Favorites erased on reboot

### ISSUE THREAD

**Issue by crunchbury** [zigurana/EmulationStation#22]
Hi,
Should I expect that favorites I've set up within the EmulationStation interface are stored on exit? They don't seem to be, so I'm wondering if there's a setting I can change. Thanks!

**Comment by zigurana** [comment]
Hey, they are stored in the gameslists xml files. So as long as you exit ES
via 'quit ES'  rather than F4 or pulling the plug outright, it should be
saved there.

If that is not the case, can you check if 1) other edits to metadata stick,
2) if the kid, hidden, favorite tags are written to the xml file at all,
and finally 3) if you (or rather: ES) have/has write access to these files.

Op di 26 jul. 2016 12:18 schreef crunchbury notifications@github.com:

**Comment by crunchbury** [comment]
Thank you. This seems to have addressed the issue.
