### ISSUE TITLE
Update from source loses kids/kiosk options

### ISSUE THREAD

**Issue by mrnohr** [zigurana/EmulationStation#34]
I tried to "Update from source" for this package, and after it pulled down the code and rebuilt, and after I got back to the main ES screens, I had lost all the custom menu options for emulationstation-kids (UI Mode, etc). It seems like I was put back into stock emulationstation.

Here are the steps:
1. RetroPie Setup
2. Manage Packages
3. Manage experimental packages
4. emulationstation-kids
5. Update from source

**Comment by zigurana** [comment]
Ok, just to see if this is due to some re-installation or just a logical that has been re-set, can you:
- Reinstall from sources (again, I've just updated the README.md)
- Try and hunt down the README.md file that should just have been pulled in from github.
  (unfortunately, I have no clue where it might be, that is totally opaque in the nested RetroPie helper functions hierargy)
- check if it says "EmulationStation - KidMode UI" on the top line, rather than just "Emulationstation"

If so, then the file is at least there, but there might be another version of ES being called.
If not, well then we have another issue.
I need to run right now, but will get back to this asap.

**Comment by mrnohr** [comment]
Until I can do a new build for testing, I just moved the kids version back under /usr/bin.

There were 2 builds:

```
/opt/retropie/supplementary/emulationstation-kids/emulationstation
/opt/retropie/supplementary/emulationstation/emulationstation
```

I linked to the kids version:

```
sudo mv /usr/bin/emulationstation /usr/bin/emulationstation.backup
sudo ln -s /opt/retropie/supplementary/emulationstation-kids/emulationstation /usr/bin/emulationstation
```

**Comment by mrnohr** [comment]
Just as another clue, when I just updated emulationstation-kids again, the file at `/usr/bin/emulationstation` was overwritten.

**Comment by Crescendo-BLYAT** [comment]
do I need to keep the stock ES when I use this?
coz I hate wasting space....

**Comment by zigurana** [comment]
This issue is most likely related to the installation scripts for ES used by RetroPie, not looking further into this, please open a new issue if you feel this problem is still relevant.
