### ISSUE TITLE
Emulation Station New Release. Advice?

### ISSUE THREAD

**Issue by Jadelutis** [zigurana/EmulationStation#52]
As you know from a previous issue emulation station has updated. You said you had no plans to update kiosk mode. Could you help or direct me to a guide on updating the existing script.

**Comment by zigurana** [comment]
Hey, I am currently on holidays, will get back to you in about a week or
so.

Op wo 2 aug. 2017 03:06 schreef Jadelutis <notifications@github.com>:

**Comment by Jadelutis** [comment]
Are you back from vacation? 25days!

**Comment by zigurana** [comment]
Hey @jadelutis, apologies for the late reply.

I do not think update the current Kid-modes branch is a feasible exercise, nor a particularly useful one.

The main reason for not wanting to spend anymore time in updating my branch with the latest developments on the Retropie-master is that I much rather would work towards bringing the kids /kiosk modes to the master branch.

This might seem like the same thing at first glance, but behind the scenes it requires a new (and less buggy) implementation of my earlier work.

So that will take some time, but in the end we will end up with the same set of features, in a healthier code-base that is easier to maintain.

If you want to help out, I would advise you to keep a look at the Retropie  forum and the retropie-emulationstation repo, to see what is brewing, and maybe contribute by testing the early versions of the work that we do.

Thanks!
